// Generated by github.com/hypermusk/hypermusk
// DO NOT EDIT

#import <Foundation/Foundation.h>


@interface Api : NSObject
@property (nonatomic, strong) NSString * baseURL;
@property (nonatomic, assign) BOOL verbose;
@property (nonatomic, assign) NSTimeInterval requestTimeoutInterval;
+ (Api *) get;

@end



// --- UseMap ---
@interface UseMap : NSObject<NSCoding>

@property (nonatomic, strong) NSDictionary * map;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- ReservedKeywordsForObjC ---
@interface ReservedKeywordsForObjC : NSObject<NSCoding>

@property (nonatomic, strong) NSString * New;
@property (nonatomic, strong) NSString * Alloc;
@property (nonatomic, strong) NSString * Copy;
@property (nonatomic, strong) NSString * MutableCopy;
@property (nonatomic, strong) NSString * Description;
@property (nonatomic, strong) NSString * normalName;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end


// === Interfaces ===

// --- AuthorizeParams ---
@interface ServiceAuthorizeParams : NSObject

@property (nonatomic, strong) NSString * name;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- AuthorizeResults ---
@interface ServiceAuthorizeResults : NSObject

@property (nonatomic, strong) UseMap * useMap;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PermiessionDeniedParams ---
@interface ServicePermiessionDeniedParams : NSObject


- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- PermiessionDeniedResults ---
@interface ServicePermiessionDeniedResults : NSObject

@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- GetReservedKeywordsForObjCParams ---
@interface ServiceGetReservedKeywordsForObjCParams : NSObject


- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end

// --- GetReservedKeywordsForObjCResults ---
@interface ServiceGetReservedKeywordsForObjCResults : NSObject

@property (nonatomic, strong) ReservedKeywordsForObjC * r;
@property (nonatomic, strong) NSError * err;

- (id) initWithDictionary:(NSDictionary*)dict;
- (NSDictionary*) dictionary;

@end


@interface Service : NSObject- (NSDictionary*) dictionary;

- (ServiceAuthorizeResults *) authorize:(NSString *)name;
- (void) authorize:(NSString *)name success:(void (^)(ServiceAuthorizeResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;

- (NSError *) permiessionDenied;
- (void) permiessionDenied:(void (^)(NSError *error))successBlock failure:(void (^)(NSError *error))failureBlock;

- (ServiceGetReservedKeywordsForObjCResults *) getReservedKeywordsForObjC;
- (void) getReservedKeywordsForObjC:(void (^)(ServiceGetReservedKeywordsForObjCResults *results))successBlock failure:(void (^)(NSError *error))failureBlock;
@end

